### ISSUE TITLE
Keep `top_levels()` here?

### ISSUE THREAD

**Issue by billdenney** [sfirke/tabyl#7]
When moving functions, I pulled `top_levels()` over here rather than leaving it in `janitor`. That felt like a more natural fit to me. But, I noticed while cleaning up the `pkgdown` files that you had categorized it differently.

Which package do you think is a better fit for `top_levels()`?

**Comment by sfirke** [comment]
This poor function, I had high hopes for it and then never used it. I should make sure there's an example with Likert scale survey data, that's where it was meant to be used -- group top-2 agree, neutral, top-2 disagree.  Too niche a function.

Anyway I agree with you, let's put it in `tabyl` since it's a similar function: it tallies, not cleans.

**Comment by billdenney** [comment]
Ha! Sounds good.
